spring.application.name=matchmaking

spring.graphql.graphiql.enabled=true
spring.graphql.path=/graphql
spring.graphql.schema.locations=classpath*:graphql/
dgs.graphql.schema-locations=classpath*:graphql/**/*.graphqls
spring.graphql.schema.introspection.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html

# RabbitMQ: локальный брокер для публикации событий
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.template.observation-enabled=true

logging.charset.console=UTF-8
